export const items =  [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 14",
      imgSrc: 'https://m.media-amazon.com/images/I/611mRs-imxL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Red',
      price: '58999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice] Notebookpro Max",
      imgSrc: 'https://m.media-amazon.com/images/I/712mZ6RXCQL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '47399',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/415gV21fNCL._SX300_SY300_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Xiaomi Pad 6| Qualcomm Snapdragon 870| ',
      price: '26499',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/315vs3rLEZL._SY445_SX342_QL70_FMwebp_.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'Apple iPhone 13 (128GB) - Green',
      price: '52,999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm)',
      price: '49999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Lenovo IdeaPad Slim 5 ",
      imgSrc: 'https://m.media-amazon.com/images/I/417PL2mg8+L._SX300_SY300_.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm) ',
      price: '60190',
    },

    {
      id: 12,
      category: 'tablets',
      title: "Apple iPad Pro 11″ (4th Generation)",
      imgSrc: 'https://m.media-amazon.com/images/I/81S05k6p0xL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },
    {
      id: 14,
      category: 'laptops',
      title: "Lenovo IdeaPad 1",
      imgSrc: 'https://m.media-amazon.com/images/I/71bDJ9wxxWL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Lenovo IdeaPad 1 AMD Ryzen 5 5500U 15.6" HD',
      price: '40990',
    },
  
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/61vsK7h3zVL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display',
      price: '22999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Apple iPhone 15",
      imgSrc: 'https://m.media-amazon.com/images/I/71v2jVh6nIL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Apple iPhone 15 (128GB) - Pink',
      price: '72299',
    },
    
    {
      id: 8,
      category: 'laptops',
      title: "HP Pavilion Gaming Laptop 11th Gen",
      imgSrc: 'https://m.media-amazon.com/images/I/51D0RrFXFEL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'HP Pavilion Gaming 11th Gen Intel Core i5 15.6"(39.6cm)',
      price: '68999',
    },
    {
      id: 10,
      category: 'mobiles',
      title: "Samsung Galaxy S24 Ultra 5G AI Smartphone ",
      imgSrc: 'https://m.media-amazon.com/images/I/71CXhVhpM0L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: ' Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Black, 12GB, 512GB Storage)',
      price: '139999',
    },
    {
      id: 15,
      category: 'laptops',
      title: "ASUS ROG Flow X13",
      imgSrc: 'https://m.media-amazon.com/images/I/61mI-ghw8mL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'ASUS ROG Flow X13 (2022), 13.4" (34.03 cm) FHD+ 16:10',
      price: '84990',
    },
     {
      id: 13,
      category: 'tablets',
      title: "OnePlus Pad",
      imgSrc: 'https://m.media-amazon.com/images/I/51oj5gE7P+L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'OnePlus Pad Go 28.85cm (11.35 inch)' ,
      price: '23999',
    }, 
    
    {
      id: 16,
      category: 'mobiles',
      title: "Samsung Galaxy S24 Ultra 5G AI Smartphone",
      imgSrc: 'https://m.media-amazon.com/images/I/81njZjDqc6L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: ' Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Gray, 12GB, 1TB Storage)',
      price: '159999',
    },
    {
      id: 13,
      category: 'tablets',
      title: "Apple iPad (10th Generation)",
      imgSrc: 'https://m.media-amazon.com/images/I/61uA2UVnYWL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple iPad (10th Generation): with A14 Bionic chip',
      price: '36900',
    },
    {
      id: 15,
      category: 'laptops',
      title: "Lenovo V15 ",
      imgSrc: 'https://m.media-amazon.com/images/I/31uLEZHhMDL._SX522_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: ' Lenovo V15 Intel Celeron N4500 15.6" (39.62 cm)',
      price: '21600',
    },
    {
      id: 11,
      category: 'mobiles',
      title: "Samsung Galaxy S24 Ultra 5G AI Smartphone",
      imgSrc: 'https://m.media-amazon.com/images/I/81NEVf26quL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Samsung Galaxy S24 Ultra 5G AI Smartphone (Titanium Violet, 12GB, 512GB Storage)',
      price: '139999',
    }
    ,
    {
      id: 17,
      category: 'mobiles',
      title: 'OnePlus 12 5G',
      imgSrc: 'https://m.media-amazon.com/images/I/61Jz5FQ0-OL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'OnePlus 12 5G (16GB RAM, 512GB Storage) – premium flagship performance',
      price: '64999',
    },
    {
      id: 18,
      category: 'laptops',
      title: 'Apple MacBook Air M2',
      imgSrc: 'https://m.media-amazon.com/images/I/71an9eiBxpL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air with M2 chip, 13.6-inch Liquid Retina display',
      price: '109999',
    },
    {
      id: 19,
      category: 'tablets',
      title: 'Samsung Galaxy Tab S9',
      imgSrc: 'https://m.media-amazon.com/images/I/61R3QcF8PGL._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Samsung Galaxy Tab S9 Wi-Fi – flagship AMOLED tablet experience',
      price: '81999',
    },
    {
      id: 20,
      category: 'laptops',
      title: 'ASUS Zenbook 14 OLED',
      imgSrc: 'https://m.media-amazon.com/images/I/71M+ClV0l0L._SX679_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'ASUS Zenbook 14 OLED with Intel Core Ultra and premium portability',
      price: '92990',
    }
  ]